// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
// Use the standard anon key env var name expected in Vite apps
const SUPABASE_ANON_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

if (import.meta.env.DEV) {
  if (!SUPABASE_URL) {
    // eslint-disable-next-line no-console
    console.warn("[Supabase] Missing VITE_SUPABASE_URL env var");
  }
  if (!SUPABASE_ANON_KEY) {
    // eslint-disable-next-line no-console
    console.warn("[Supabase] Missing VITE_SUPABASE_ANON_KEY env var");
  }
}

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_ANON_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});